name: Check Console Logs

on:
  pull_request:
    branches:
      - main

jobs:
  check-logs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for console.log statements
      run: |
        grep -rnw 'src/' -e 'console.log' | while read line; do
          echo "::warning file=${line%%:*},line=${line#*:},col=1::Found console.log"
        done

        # The job will complete successfully, but with warnings if console.log statements are found.
