name: Check Console Logs

on:
  pull_request:
    branches:
      - main

jobs:
  check-logs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for console.log statements
      run: |
        LOGS_FOUND=0
        while IFS= read -r line
        do
          echo "::error ::console.log found: $line"
          LOGS_FOUND=1
        done < <(grep -rnw 'src/' -e 'console.log')

        if [ "$LOGS_FOUND" -ne "0" ]; then
          exit 1
        else
          echo "No console.log statements found."
        fi
