name: Release Obsidian plugin

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1

            - name: Add extra dependency
              run: |
                  node -e "
                  const fs = require('fs');
                  const packageJson = JSON.parse(fs.readFileSync('./package.json', 'utf-8'));
                  packageJson.dependencies['papa-ts'] = '0.5.2';
                  fs.writeFileSync('./package.json', JSON.stringify(packageJson, null, 2));
                  "

            - name: Install dependencies
              run: bun install

            - name: Build plugin
              run: bun run build

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  tag="${GITHUB_REF#refs/tags/}"

                  gh release create "$tag" \
                    --title="$tag" \
                    --draft \
                    build/prod/main.js manifest.json build/prod/styles.css
